
import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
// import {Teachers} from '@/font/google'
import { SessionProvider } from "next-auth/react";
import type { AppProps } from "next/app";
import SessionProviderWrapper from "@/components/SessionProviderWrapper";
export const metadata: Metadata = {
  title: "Physics Bugle",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  session,
}: Readonly<{
  children: React.ReactNode,
  session: any,
}>) {
  return (
    <html lang="en">
      <SessionProviderWrapper>
        <body>
          <Navbar />
          <main className="relative overflow-hidden">
            {children}
          </main>
          <Footer />
        </body>
      </SessionProviderWrapper>
    </html>
  );
}
