# Generated by Django 5.0.6 on 2024-08-05 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.CharField(default='Physics Bugle Article', max_length=200),
        ),
    ]
