# Generated by Django 5.0.6 on 2024-08-05 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='image',
        ),
        migrations.AddField(
            model_name='article',
            name='image_url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
