# Generated by Django 5.0.6 on 2024-08-10 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_remove_article_image_article_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image_url',
            field=models.URLField(default='https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.geeksforgeeks.org%2Fphysics%2F&psig=AOvVaw0tl4v0FWrMmwTng9jM68pa&ust=1722961817608000&source=images&cd=vfe&opi=89978449&ved=0CBEQjRxqFwoTCKiG3Jij3ocDFQAAAAAdAAAAABAJ'),
        ),
    ]
