# Generated by Django 5.0.6 on 2024-08-01 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentProxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_id', models.CharField(max_length=200)),
                ('course_id', models.CharField(max_length=200)),
                ('video', models.URLField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('questions', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Content',
                'verbose_name_plural': 'Contents',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('department', models.CharField(choices=[('MATH', 'Mathematics'), ('PHYS', 'Physics')], max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='courses.course')),
            ],
        ),
    ]
